parameters:

services:
    # override default voter
    #knp_menu.voter.router:
    #    class: Becklyn\RadBundle\Service\SimpleRouteVoter
    #    calls:
    #        - [ setContainer, [@service_container] ]
    #    tags:
    #        - { name: knp_menu.voter}


    form.type_extension.help_message:
        class: Becklyn\RadBundle\Type\Extension\GenericTypeExtension
        tags:
            - { name: form.type_extension, alias: form }


    twig.extension.becklyn.rad.pagination:
        class: Becklyn\RadBundle\Service\PaginationTwigExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]


    twig.extension.becklyn.rad.utils:
        class: Becklyn\RadBundle\Service\UtilsTwigExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]
