parameters:

services:
    # override default voter
    #knp_menu.voter.router:
    #    class: Becklyn\RadBundle\Service\SimpleRouteVoter
    #    calls:
    #        - [ setContainer, ["@service_container"] ]
    #    tags:
    #        - { name: knp_menu.voter}


    becklyn_rad.form.type_extension.help_message:
        class: Becklyn\RadBundle\Form\Type\HelpMessageFormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }


    becklyn_rad.twig.utils:
        class: Becklyn\RadBundle\Service\UtilsTwigExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }


    becklyn_rad.listener.root_template:
        class: Becklyn\RadBundle\EventListener\RootTemplateListener
        arguments: ["@service_container"]
        tags:
            - { name: kernel.event_subscriber }


    becklyn_rad.view.root_template_guesser:
        class: Becklyn\RadBundle\View\RootTemplateGuesser
