parameters:

services:
    # override default voter
    #knp_menu.voter.router:
    #    class: OAGM\BaseBundle\Service\SimpleRouteVoter
    #    calls:
    #        - [ setContainer, [@service_container] ]
    #    tags:
    #        - { name: knp_menu.voter}


    form.type_extension.help_message:
        class: OAGM\BaseBundle\Type\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }