parameters:

services:
    # override default voter
    #knp_menu.voter.router:
    #    class: OAGM\BaseBundle\Service\SimpleRouteVoter
    #    calls:
    #        - [ setContainer, [@service_container] ]
    #    tags:
    #        - { name: knp_menu.voter}


    form.type_extension.help_message:
        class: OAGM\BaseBundle\Type\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }


    twig.extension.oagm.base_bundle.pagination:
        class: OAGM\BaseBundle\Service\PaginationTwigExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]


    twig.extension.oagm.base_bundle.utils:
        class: OAGM\BaseBundle\Service\UtilsTwigExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]