parameters:

services:
    # override default voter
    #knp_menu.voter.router:
    #    class: Becklyn\RadBundle\Service\SimpleRouteVoter
    #    calls:
    #        - [ setContainer, [@service_container] ]
    #    tags:
    #        - { name: knp_menu.voter}


    becklyn_rad.form.type_extension.help_message:
        class: Becklyn\RadBundle\Type\Extension\GenericTypeExtension
        tags:
            - { name: form.type_extension, alias: form }


    becklyn_rad.twig.pagination:
        class: Becklyn\RadBundle\Service\PaginationTwigExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]


    becklyn_rad.twig.utils:
        class: Becklyn\RadBundle\Service\UtilsTwigExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]


    becklyn_rad.listener.root_template:
        class: Becklyn\RadBundle\EventListener\RootTemplateListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: [@service_container]


    becklyn_rad.view.root_template_guesser:
        class: Becklyn\RadBundle\View\RootTemplateGuesser
