services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Form
    Becklyn\RadBundle\Form\Type\HelpMessageFormTypeExtension: ~
    Becklyn\RadBundle\Twig\GoogleAnalyticsTwigExtension: ~
