parameters:

services:

    becklyn_rad.form.type_extension.help_message:
        class: Becklyn\RadBundle\Form\Type\HelpMessageFormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }


    becklyn_rad.twig.utils:
        class: Becklyn\RadBundle\Twig\UtilsTwigExtension
        tags:
            - { name: twig.extension }


    # Security / Authentication
    becklyn_rad.authentication_helper:
        class: Becklyn\RadBundle\Security\AuthenticationHelper
        arguments:
            - "@security.token_storage"
            - "@session"
