parameters:

services:
    # override default voter
    #knp_menu.voter.router:
    #    class: OAGM\BaseBundle\Service\SimpleRouteMenuVoter
    #    calls:
    #        - [ setContainer, [@service_container] ]
    #    tags:
    #        - { name: knp_menu.voter}