services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\RadBundle\:
        resource: ../../*
        exclude: ../../{Entity,Exception,Pagination,Resources,BecklynRadBundle.php}
