services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\RadBundle\:
        resource: ../../*
        exclude: ../../{Entity,Exception,Pagination/Data,Resources,BecklynRadBundle.php}

    Becklyn\RadBundle\Usages\EntityUsagesFinder:
        $finders: !tagged_iterator entity_usages.provider

    Becklyn\RadBundle\Command\CommandHelper:
        $eventManager: "@doctrine.dbal.default_connection.event_manager"
