services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\RadBundle\:
        resource: ../../*
        exclude: ../../{Entity,Exception,Pagination/PaginatedList.php,Pagination/Pagination.php,Resources,BecklynRadBundle.php}
